Finalização do layout da tela cadastro
JEAM-Team/smartcash-mobile pull request #17
Opened 2022-05-04 03:31 UTC by aiseu

2022-05-05 00:25 UTC, JHenrique404 requested changes

2022-05-05 00:25 UTC, JHenrique404 commented on app/src/main/java/com/example/smartcash/MainActivity.java
> +        setContentView(R.layout.activity_cadastro);
mudar pra setContentView(login);

2022-05-06 23:48 UTC, aiseu commented on app/src/main/java/com/example/smartcash/MainActivity.java
> +        setContentView(R.layout.activity_cadastro);
Resolvido

2022-05-06 23:48 UTC, aiseu commented on app/src/main/java/com/example/smartcash/MainActivity.java
> +        setContentView(R.layout.activity_cadastro);
Resolvido

2022-05-07 18:39 UTC, JHenrique404 requested changes

2022-05-07 18:39 UTC, JHenrique404 commented on app/src/main/java/com/example/smartcash/MainActivity.java
> -        setContentView(R.layout.login);
volta aq pra login tbm faz favo

2022-05-08 01:08 UTC, merged